version: '3'

volumes:
 data:

services:
  webapplication:
   image: ${DOCKER_REGISTRY-}api
   build:
     context: .
     dockerfile: .
   ports:
    - "8081:80"
   depends_on:
    - database

  dbPostgres:
   image: postgres:latest
   restart: always
   ports: 
    - 5441:5432
   environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: BancoDeUsers 
   volumes:
   - data:/var/lib/postgresql/data

