version: '3.9'

services:
  webapplication:
   image: ${DOCKER_REGISTRY-}webapplication
   build:
     context: .
     dockerfile: .
   ports:
    - "8081:80"
   depends_on:
    - database

  database:
   image: postgres:14
   ports: 
    - 5432:5432
   environment:
    - POSTGRES_PASSWORD=123456

