version: '3.8'

volumes:
 data:

services:
  webapplication:
   image: ${DOCKER_REGISTRY-}api
   build:
     context: .
     dockerfile: ./Dockerfile
   ports:
    - "8081:80"
   depends_on:
    - dbpostgres
   links:
     - dbpostgres
   networks:
      - postgres-compose-network

  dbpostgres:
   image: postgres:latest
   restart: always
   ports: 
    - 5441:5432
   expose: 
    - 5441
   environment:
     - POSTGRES_DB=BancoDeUsers
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=supersecretpassword
   volumes:
   - data:/var/lib/postgresql/data
   networks:
   - postgres-compose-network

networks: 
 postgres-compose-network: 
  driver: bridge

